# Generated by Django 4.2.1 on 2023-05-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supercars', '0002_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='images/nocar.jpg', upload_to='images/'),
        ),
    ]
