# Generated by Django 4.2.1 on 2023-06-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supercars', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='make',
            field=models.CharField(default='', max_length=100),
        ),
    ]
