# Generated by Django 4.2.1 on 2023-06-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supercars', '0004_alter_post_make'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
