# Generated by Django 4.2.1 on 2023-06-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supercars', '0005_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='images/nocar.jpg', upload_to='images/'),
        ),
    ]
